# Copyright © KhulnaSoft Dev <info@khulnasoft.com>
#
# SPDX-License-Identifier: CC0-1.0

# This file is maintained in https://github.com/deepSquads/meta/
github: [khulnasoft-bot, deepSquads]
custom: https://deepquads.github.io/donate/
liberapay: Deepquads
open_collective: deepquads
polar: deepSquads
