services:
  deepquads:
    image: deepquads/deepquads
    tmpfs:
    - /run
    - /tmp
    - /app/cache
    volumes:
    - type: volume
      source: deepquads-data
      target: /app/data
    env_file:
    - ./environment
    restart: always
    read_only: true
    depends_on:
    - database
    - cache
    - deepquads-celery-beat
    environment:
      DEEPSQUADS_SERVICE: web
  deepquads-celery-backup:
    image: deepquads/deepquads
    tmpfs:
    - /run
    - /tmp
    - /app/cache
    volumes:
    - type: volume
      source: deepquads-data
      target: /app/data
      volume:
        nocopy: true
    env_file:
    - ./environment
    restart: always
    read_only: true
    depends_on:
    - database
    - cache
    - deepquads-celery-beat
    environment:
      DEEPSQUADS_SERVICE: celery-backup
  deepquads-celery-beat:
    image: deepquads/deepquads
    tmpfs:
    - /run
    - /tmp
    - /app/cache
    volumes:
    - type: volume
      source: deepquads-data
      target: /app/data
      volume:
        nocopy: true
    env_file:
    - ./environment
    restart: always
    read_only: true
    depends_on:
    - database
    - cache
    environment:
      DEEPSQUADS_SERVICE: celery-beat
  deepquads-celery-celery:
    image: deepquads/deepquads
    tmpfs:
    - /run
    - /tmp
    - /app/cache
    volumes:
    - type: volume
      source: deepquads-data
      target: /app/data
      volume:
        nocopy: true
    env_file:
    - ./environment
    restart: always
    read_only: true
    depends_on:
    - database
    - cache
    - deepquads-celery-beat
    environment:
      DEEPSQUADS_SERVICE: celery-celery
  deepquads-celery-memory:
    image: deepquads/deepquads
    tmpfs:
    - /run
    - /tmp
    - /app/cache
    volumes:
    - type: volume
      source: deepquads-data
      target: /app/data
      volume:
        nocopy: true
    env_file:
    - ./environment
    restart: always
    read_only: true
    depends_on:
    - database
    - cache
    - deepquads-celery-beat
    environment:
      DEEPSQUADS_SERVICE: celery-memory
  deepquads-celery-notify:
    image: deepquads/deepquads
    tmpfs:
    - /run
    - /tmp
    - /app/cache
    volumes:
    - type: volume
      source: deepquads-data
      target: /app/data
      volume:
        nocopy: true
    env_file:
    - ./environment
    restart: always
    read_only: true
    depends_on:
    - database
    - cache
    - deepquads-celery-beat
    environment:
      DEEPSQUADS_SERVICE: celery-notify
  deepquads-celery-translate:
    image: deepquads/deepquads
    tmpfs:
    - /run
    - /tmp
    - /app/cache
    volumes:
    - type: volume
      source: deepquads-data
      target: /app/data
      volume:
        nocopy: true
    env_file:
    - ./environment
    restart: always
    read_only: true
    depends_on:
    - database
    - cache
    - deepquads-celery-beat
    environment:
      DEEPSQUADS_SERVICE: celery-translate
  database:
    image: postgres:16-alpine
    env_file:
    - ./environment
    volumes:
    - postgres-data:/var/lib/postgresql/data
    restart: always
  cache:
    image: redis:7-alpine
    restart: always
    read_only: true
    command: [redis-server, --save, '60', '1']
    volumes:
    - redis-data:/data
volumes:
  deepquads-data: {}
  postgres-data: {}
  redis-data: {}
