#!/bin/sh
set -e
docker compose exec -T --user deepquads --env CI_BASE_DIR=/tmp --env CI_DATABASE=postgresql --env CI_DB_HOST=database --env CI_DB_NAME=deepquads --env CI_DB_USER=deepquads --env CI_DB_PASSWORD=deepquads --env DJANGO_SETTINGS_MODULE=deepquads.settings_test deepquads deepquads collectstatic --noinput
docker compose exec -T --user deepquads --env CI_BASE_DIR=/tmp --env CI_DATABASE=postgresql --env CI_DB_HOST=database --env CI_DB_NAME=deepquads --env CI_DB_USER=deepquads --env CI_DB_PASSWORD=deepquads --env DJANGO_SETTINGS_MODULE=deepquads.settings_test deepquads deepquads test --noinput deepquads
RET=$?
if [ $RET -ne 0 ] ; then
    docker compose logs
    exit $RET
fi
